### ISSUE TITLE
Peptide omega failing for PDBe entry 5TIG

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#165]
The validation plot for the PDBe entry 5TIG does not show pept. omega values. We are getting the following error after running `mc.peptide_omega_analysis`:

```
EXCEPTION RAISED IN peptide_omega_analysis, RuntimeError: index out of bounds
```
This happens when loading the cif file but not the pdb file.

**Comment by pemsley** [comment]
Fixed in 1f2ee51ade2ce6b5ad013183644a6bfbd9aacbd0
