### ISSUE TITLE
Using style `CA+LIGANDS` to get bond mesh does not follow `mc.set_draw_missing_residue_loops`

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#167]
After using `mc.set_draw_missing_residue_loops(false)` we still get missing loops when using `mc.get_bonds_mesh_instanced` and style `CA+LIGANDS`. Everything works as expected if style is `COLOUR-BY-CHAIN-AND-DICTIONARY`.

**Comment by LucreziaCatapano** [comment]
It seems that when the "Show missing loop" widget is toggled, then the code is checking to see if Bonds are being displayed and updates the mesh. However, when CAs are being displayed, this does not happen (I think that it should). There was a bug also in libcootapi. I have pushed a fix for that, but Paul has not merge it yet. You can though of course!

**Comment by FilomenoSanchez** [comment]
Thanks, you're right Moorhen was not asking to redraw the mesh. Fixed in https://github.com/moorhen-coot/Moorhen/commit/abb260c97afcff43ec1b414da201ef493f52b83b. Anyway the problem still persists in the api so I'll wait until your fix is merged by Paul before closing this issue.

**Comment by pemsley** [comment]
OK, 16e5c87daec006f853f6a64c7f5df44c387ecb90 has been merged.

**Comment by FilomenoSanchez** [comment]
Thanks, closing now.
