### ISSUE TITLE
Error fetching EMDB entry 17257

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#260]
Currently `File -> Fetch from EMDB -> 17257 -> OK` does not seem to work. This problem might extend to other EMDB maps.

**Comment by FilomenoSanchez** [comment]
@pemsley & @LucreziaCatapano I'm now assigning this to you as this in fact a `libcoot` api issue. I am getting the following exception back from `molecules_container::read_ccp4_map`.
```
RuntimeError: index out of bounds
```
So far I've only observed this with EMDB entry 17257, other entries are loaded OK. Opening this file in desktop coot also results in no map being displayed.

**Comment by pemsley** [comment]
If the axis order is X,Y,Z then libcootapi can use a fast map parser - and that map parser can also read .gz files (thanks Jakub).

There is no CCP4 map parsing for .gz files.

The axis order of 17257 is not X,Y,Z (it's Z,Y,X).

I think that 0e9cf057abf152906f72483954d9e40d36ee92f5 fixes the invalid map read, so at least libcootapi doesn't crash now.

**Comment by FilomenoSanchez** [comment]
Thanks, I wonder if I can instead catch the -3 status and attempt to decompress the file myself instead of deferring this to the user. Anyway this is now a Moorhe UI issue I think.
