### ISSUE TITLE
Importing a ligand crashes the app

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#27]
Clicking on Ligand -> Import dictionary -> From monomer library -> NUT -> OK
Throws the error:
```
Uncaught (in promise) TypeError: this.enerLib is undefined
```
The error occurs regardless of the chosen ligand.

**Comment by stuartjamesmcnicholas** [comment]
Fixed in aa1d99102270f3a8413df3db471a1873c69e1258
