### ISSUE TITLE
Tryptophan NE1 is not hidden by `add_to_non_drawn_bonds`

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#275]
After calling `molecules_container_t::add_to_non_drawn_bonds` for a given selection we still get bonds corresponding with tryptophan's NE1. Best way to reproduce is use one of the methods that calls this function, like for example drag atoms on a TRP residue.

**Comment by pemsley** [comment]
Confirmed.

**Comment by FilomenoSanchez** [comment]
Fixed in https://github.com/pemsley/coot/commit/5016d67ea8c58f0c4a1950629b593602550787d8
