### ISSUE TITLE
`molecules_container_t::refine_residues_using_atom_cid` does not trigger a map recalculation when using mode 'LITERAL'

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#276]
After connecting a molecule with the maps for updates, the maps do not get recalculated when using `refine_residues_using_atom_cid` if the mode is set to 'LITERAL'.

**Comment by pemsley** [comment]
Added the flag to update maps in `molecules_container_t::refine_residues_using_atom_cid()`, ecf0019534a0434323d9398ec8566fd78de8617b Please give it another go.

**Comment by FilomenoSanchez** [comment]
It seems this is still not working @pemsley

**Comment by FilomenoSanchez** [comment]
OK my bad, I can confirm https://github.com/pemsley/coot/commit/ecf0019534a0434323d9398ec8566fd78de8617b fixes the issue. Now the problem is in the front-end, we are not triggering score updates after refinement.
