### ISSUE TITLE
Molten-zone atoms have missing loops drawn

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#294]
The molten-zone atoms have missing loops drawn. We should call the bonds mesh function with `draw_missing_residue_loops=false`

**Comment by FilomenoSanchez** [comment]
I've tried calling `mc.set_draw_missing_residue_loops(false)` but the missing loops are still drawn. I think the problem is that `molecules_container.refine` which we use in the animated refinement returns a `instanced_mesh_t` that contains the missing loops regardless of what we set with `set_draw_missing_residue_loops`. I'm switching this ticket over to you now.

**Comment by pemsley** [comment]
OK!
And I'll switch it over to Lucrezia.

**Comment by pemsley** [comment]
OK, I think I've fixed it with 8103f9d76b4970a683eae2936227c9af24735d45.

**Comment by FilomenoSanchez** [comment]
Confirmed, fixed in https://github.com/pemsley/coot/commit/8103f9d76b4970a683eae2936227c9af24735d45. Closing this now.
