### ISSUE TITLE
Colour rules do not apply to atoms, only residues

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#350]
Creating user defined colours with `molcules_container_t.set_user_defined_atom_colour_by_selection` for a given atom selection (such as `//A/*/[C]`) does not seem to work. Instead colour rules seem to apply only at the residue level.

**Comment by pemsley** [comment]
Please give it another go.
https://github.com/pemsley/coot/commit/ed0abc05dffbc8171f13c0e3ff89bf4b65815144
