### ISSUE TITLE
Call auto open MTZ automatically

### ISSUE THREAD

**Issue by mgaonach** [moorhen-coot/Moorhen#385]
The 'Auto open MTZ' feature is very convenient but, except if I missed it, there is no way to call it automatically from a Moorhen React app. 

For now I have duplicated the code I found in `MoorhenAutoOpenMtzMenuItem` into my app, but it would be great to be able to directly use it without duplicating. Maybe something like:

```ts
const newMap = new MoorhenMap(
  commandCentre,
  glRef,
  store
);
await newMap.autoOpenMtzFromURL(url);
```

Happy to try to make a PR if you confirm I didn't miss it somewhere.

**Comment by FilomenoSanchez** [comment]
Hi @mgaonach, there is no method in `MoorhenMap` to call auto open mtz. This is because the result of using auto open mtz is multiple maps (not just a single one) so it's not something I think belongs there as a method of a map instance. Perhaps it could be added as a static method, I'll take care of this. Anyway at the moment the best way to achieve what you want is to use the command centre directly as you've already done. Alternatively you can call `MoorhenMap.loadToCootFromMtzURL` to open the map if you know the column names you want to open, which might be less involved.

**Comment by mgaonach** [comment]
Alright, I'll keep using the commands and switch when it is implemented then. Thanks!

**Comment by FilomenoSanchez** [comment]
I have implemented this in https://github.com/moorhen-coot/Moorhen/commit/fd3c84aa5957d45c9bffaf940621d76c97a76064. It will be available with the next release.

**Comment by FilomenoSanchez** [comment]
@mgaonach FYI moorhen 0.9.0 is out now and it has a static method `MoorhenMap.autoReadMtz`. You can use it like this:
```js
        const newMaps = await MoorhenMap.autoReadMtz(file, props.commandCentre, props.glRef, props.store)
```

**Comment by mgaonach** [comment]
That's great, thanks a lot!

I am just getting an issue with typescript, it seems the `autoReadMtz` method is missing in the exported types:
```ts
import { MoorhenMap } from "moorhen";

const newMaps = await MoorhenMap.autoReadMtz(file, props.commandCentre, props.glRef, props.store)
```
This does not compile and gives me the error `Property 'autoReadMtz' does not exist on type 'typeof MoorhenMap'.ts(2339)`

If I bypass the type checking with a `any` and execute it, it does work:

```ts
import { MoorhenMap } from "moorhen";

const newMaps = await (MoorhenMap as any).autoReadMtz(file, props.commandCentre, props.glRef, props.store) as MoorhenMap[];
```

So it seems to be only an issue with the types I get when doing `import { MoorhenMap } from "moorhen";`. Maybe this is not the right way to import it?

**Comment by FilomenoSanchez** [comment]
Thanks for letting me know @mgaonach, this seems to be an oversight on my side. I've pushed a fix now, it will be there in the next release. In the meantime you may want use `// @ts-ignore` for that line.
