### ISSUE TITLE
Refactor options in "Get monomer" and "Import ligand dictionary" menu items

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#408]
As requested, the following changes should be done to "Get monomer" and "Import ligand dictionary" menu items:
- The "Import ligand dictionary" will now always be used to import a dictionary from a local file. Therefore the "Select a source" input form will be removed.
- By default, "Get monomer" will retain the current behavior, which consists of looking for the ligand sequentially in the following sources until a match is found:
     1. Libcoot API (calls `molecules_container_t::get_monomer_and_position_at`)
     2. Local monomer library (platform-dependent, found in `public/baby-gru/monomers`)
     3. Remote monomer library (in github)
     4. PDBe chem
- A new info tooltip will be added to the "Get monomer" menu item explaining the above default behavior.
- A new switch "Select a source" will be added to the "Get monomer" menu. If turned on, then a input form will appear, letting users override the default behavior and specify a particular source for their monomer.

**Comment by pemsley** [comment]
Yes.
