### ISSUE TITLE
Error with MoorhenMap.autoReadMtz

### ISSUE THREAD

**Issue by mgaonach** [moorhen-coot/Moorhen#418]
Hello,

I just updated to the new version 0.10.0 and I am getting an error after calling `MoorhenMap.autoReadMtz`:

![image](https://github.com/user-attachments/assets/b15da246-c839-4748-a501-9c6a677384a0)

The CCP4 module that was loaded is the 32 bit one.

Opening the same files with version `0.9.4` works.

It seems the `Auto open MTZ` is broken on `https://moorhen.org/` too: when I do it there, I do not get an error but nothing happens.

**Comment by FilomenoSanchez** [comment]
Thanks for reporting this, I can reproduce the error as well.

**Comment by FilomenoSanchez** [comment]
The function `get_mtz_columns` used to be included in the front-end wasm blob (a.k.a `web_example.js`) see here:
https://github.com/moorhen-coot/Moorhen/blob/787cbb6dbfa5550f338fc26bc3ed5e60034d3fd4/wasm_src_frontend/web_example.cc#L338
This blob is no longer used, so we should include this function in the `moorhen.js` wasm blob. I tried doing this myself but the compiler complained about some missing functions/types (it went above my head). @stuartjamesmcnicholas could you take a look?

**Comment by stuartjamesmcnicholas** [comment]
Hopefully this is fixed in 909f3f70a0d2b23385f61a3e3456350280f80f7b.

**Comment by FilomenoSanchez** [comment]
Thanks @stuartjamesmcnicholas I can confirm this works now.

**Comment by mgaonach** [comment]
Thanks a lot!
