### ISSUE TITLE
Minor UI improvements

### ISSUE THREAD

**Issue by colinpalmer** [moorhen-coot/Moorhen#421]
A couple of suggestions for improvements in the UI:

- Trying to scroll the contour level with Ctrl + mouse wheel, if the active map is not displayed, nothing happens and there's no feedback for the user. It'd be helpful to display a message to say "active map not displayed, cannot change contour level" or similar
- The zoom controls don't seem to be documented anywhere. People will probably naturally discover the scroll wheel and pinch-to-zoom on a trackpad, but it'd be nice to have "Alt + click and drag vertically" documented in the "h" help text and the Moorhen Controls panel.
- It'd be great to have a search function in the Moorhen Controls panel

**Comment by FilomenoSanchez** [comment]
Thanks, these are all good suggestions I think.
