### ISSUE TITLE
There seems to be an issue with "jed flip" ing a ligand with an alt-conf

### ISSUE THREAD

**Issue by FilomenoSanchez** [moorhen-coot/Moorhen#6]
There seems to be an issue with "jed flip" ing a residue which one has split into an alternate conformer. Simple to reproduce ("Get monomer" (NUT) -> Make alternate conformation->Jed-flip). At first I hoped it was just because we were not adding the alternate conformer ID into the atom CID given to the command, but I have now pushed a change that addresses that scenario, and the atom spec now includes the alternate conf

**Comment by pemsley** [comment]
Fixed in 25b23f94c4639f25b6a2f77a57fb147e6c70cc90.

Please test at your end.

**Comment by FilomenoSanchez** [comment]
Confirmed, closing now.
